# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/string_therapy_for_material_science',
                'doc_host': 'https://alix559.github.io',
                'git_url': 'https://github.com/alix559/string_therapy_for_material_science',
                'lib_path': 'string_therapy_for_material_science'},
  'syms': { 'string_therapy_for_material_science.core': { 'string_therapy_for_material_science.core.foo': ( 'core.html#foo',
                                                                                                            'string_therapy_for_material_science/core.py')}}}
