"""Fill in a module description here

Docs: https://alix559.github.io/string_therapy_for_material_science/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['foo']

# %% ../nbs/00_core.ipynb #da4d26dd
def foo(): pass
